### ISSUE TITLE
TiC Ore not turning to chunks

### ISSUE THREAD

**Issue by erima** [DemoXinMC/FortuneOres2#3]
I've been a fan of Fortune Ores for a while and typically if I'm using TiC I turn off _other_ duplicate ore generation. So it seems like it's been working in the past, if I recall correctly. In my most recent pack I've been seeing TiC Copper and Aluminum show up as ore blocks, not a fortune ore. Using the latest versions of both Fortune Ores and TiC.

**Comment by DemoXinMC** [comment]
I'm not able to replicate this problem.  Are you using any other mods that may be affecting TConstruct ores such as IguanaTweaks?

**Comment by erima** [comment]
Interesting. I have both Iguana Tweaks and Iguana Tweaks for TiC installed, and usually do not. Looking over the configs I didn't see anything that would conflict with Fortunes ores. Which mod is it?

**Comment by DemoXinMC** [comment]
I'm not sure what mod would be causing the issue, but given that its an
edge case, if you're willing to track down which mod is causing it, I'll do
what I can to fix it on my end.
