### ISSUE TITLE
CC Mining Turtle

### ISSUE THREAD

**Issue by Mowmaster** [DemoXinMC/FortuneOres2#5]
The computercraft turtle when it mines the ore it gets it as an ore, not as a chunk like a real player would. Does Fortune Ores support fake players?
[Screenshot](http://imgur.com/AvIO5Vo)

**Comment by DemoXinMC** [comment]
ComputerCraft should be posting HarvestDropsEvent when breaking blocks.
This isn't a FakePlayer issue.

> https://github.com/DemoXinMC/FortuneOres2/issues/5
