### ISSUE TITLE
Osmium bugs. 1.10.2 version 4.0.0

### ISSUE THREAD

**Issue by BlooYed** [DemoXinMC/FortuneOres2#7]
Yo. Thought i'd let you know that for some reason Osmium is unable to get further enhanced with your mod installed (i.e can't make dust out of Osmium to double/tripple/quadruple it) And it seems that for some reason when checking the Ore-Spawns i couldn't search for "oreOsmium" in the Digital Miner. Not a clue how mods work tbh but this seems rather odd.

**Comment by DemoXinMC** [comment]
FortuneOres actively prevents other mods from registering ores that it's been config'd to support support in favor of handling their drops on it's own.  Mekanism should be using OreDict names to process things.
